config/routes.rb
Rails.application.routes.draw do
  
  
 devise_for :users 
  
  authenticate :user do
    
    resources :babies
    resources :assistants
    resources :activity_logs
    resources :activities

    get 'search/create'
    root to:'welcome#index'
    
  end


  unauthenticated :user do
    root to:'welcome#unregistered'
  end
  
end

app/models/assistant.rb
# == Schema Information
#
# Table name: assistants
#
#  id         :integer          not null, primary key
#  address    :string(255)
#  group      :string(255)
#  name       :string(255)
#  phone      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Assistant < ApplicationRecord
  has_many :activities, through: :activity_logs
  has_many :babies, through: :activity_logs
  has_many :activity_logs

  validates :name,:address,:phone,presence:true
end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  before_action :set_assistant, only: [:show, :edit, :update, :destroy]

  # GET /assistants
  # GET /assistants.json
  def index
    @assistants = Assistant.all
  end

  # GET /assistants/1
  # GET /assistants/1.json
  def show
  end

  # GET /assistants/new
  def new
    @assistant = Assistant.new
  end

  # GET /assistants/1/edit
  def edit
  end

  # POST /assistants
  # POST /assistants.json
  def create
    @assistant = Assistant.new(assistant_params)

    respond_to do |format|
      if @assistant.save
        format.html { redirect_to @assistant, notice: 'Assistant was successfully created.' }
        format.json { render :show, status: :created, location: @assistant }
      else
        format.html { render :new }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistants/1
  # PATCH/PUT /assistants/1.json
  def update
    respond_to do |format|
      if @assistant.update(assistant_params)
        format.html { redirect_to @assistant, notice: 'Assistant was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistant }
      else
        format.html { render :edit }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistants/1
  # DELETE /assistants/1.json
  def destroy
    @assistant.destroy
    respond_to do |format|
      format.html { redirect_to assistants_url, notice: 'Assistant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistant
      @assistant = Assistant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assistant_params
      params.require(:assistant).permit(:name, :group, :address, :phone)
    end
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/views/assistants/_form.html.haml
= form_for @assistant do |f|
  - if @assistant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@assistant.errors.count, "error")} prohibited this assistant from being saved:"
      %ul
        - @assistant.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :group
    = f.text_field :group
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/assistants/edit.html.haml
%h1 Editing assistant

= render 'form'

= link_to 'Show', @assistant
\|
= link_to 'Back', assistants_path

app/views/assistants/index.html.haml
%h1 Listing assistants

%table
  %thead
    %tr
      %th Name
      %th Group
      %th Address
      %th Phone
      %th
      %th
      %th

  %tbody
    - @assistants.each do |assistant|
      %tr
        %td= assistant.name
        %td= assistant.group
        %td= assistant.address
        %td= assistant.phone
        %td= link_to 'Show', assistant
        %td= link_to 'Edit', edit_assistant_path(assistant)
        %td= link_to 'Destroy', assistant, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Assistant', new_assistant_path

app/views/assistants/new.html.haml
%h1 New assistant

= render 'form'

= link_to 'Back', assistants_path

app/views/assistants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @assistant.name
%p
  %b Group:
  = @assistant.group
%p
  %b Address:
  = @assistant.address
%p
  %b Phone:
  = @assistant.phone

= link_to 'Edit', edit_assistant_path(@assistant)
\|
= link_to 'Back', assistants_path