config/routes.rb
Rails.application.routes.draw do
  
  
 devise_for :users 
  
  authenticate :user do
    
    resources :babies
    resources :assistants
    resources :activity_logs
    resources :activities

    get 'search/create'
    root to:'welcome#index'
    
  end


  unauthenticated :user do
    root to:'welcome#unregistered'
  end
  
end

app/views/partials/_filters.haml
=form_tag "search/create", method: :get,remote:true ,id:"search-form"  do
  .row
    .col-md-3
      %label Bebés
      %br
      =select_tag :baby_id, options_for_select(@babies.collect{ |u| [u.name, u.id]}.insert(0,"Selecciona un Bebé")),class:"custom-select"
    .col-md-3
      %label Asistentes
      %br
      =select_tag :assistant_id, options_for_select(@assistants.collect{ |u| [u.name, u.id]}.insert(0,"Selecciona un asistente")),class:"custom-select"
    .col-md-3
      %label Estatus
      %br
      =select_tag :status, options_for_select( ["Todos" ,"Terminado" ,"En progreso"] ),class:"custom-select"
    .col-md-3
      .mt-2
      %br 
        =content_tag :button, type: :submit do
          Filtrar

app/views/partials/_flashs.haml
%p.large-padding.roboto.red.white-text.text-center.alert{:style => "#{'display:none;' if alert.nil?} margin-bottom: 0px;"}
  = alert
  %span.close-parent{:style => "float: right; cursor: pointer;"} X
%p.large-padding.roboto.blue.white-text.text-center.alert{:style => "#{'display:none;' if notice.nil?} margin-bottom: 0px;"}
  = notice
  %span.close-parent{:style => "float: right; cursor: pointer;"} X

app/views/partials/_navigation.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to root_path ,class:"navbar-brand" do 
    Kinedu
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      -if user_signed_in?
        %li.nav-item.active
          =link_to "Bebés", babies_path ,class:" nav-link"
        %li.nav-item
          =link_to "Actividades", activities_path ,class:" nav-link"
        %li.nav-item
          =link_to "Log de actividades", activity_logs_path ,class:" nav-link"
        %li.nav-item
          
          =link_to "Cerrar sesion", destroy_user_session_path, method: :delete,class:" nav-link"
      -else
        %li.nav-item.active
          =link_to "Iniciar sesion", new_user_session_path ,class:" nav-link"
        %li.nav-item
          =link_to "Crear cuenta", new_user_registration_path ,class:" nav-link"

      