config/routes.rb
Rails.application.routes.draw do
  
  
 devise_for :users 
  
  authenticate :user do
    
    resources :babies
    resources :assistants
    resources :activity_logs
    resources :activities

    get 'search/create'
    root to:'welcome#index'
    
  end


  unauthenticated :user do
    root to:'welcome#unregistered'
  end
  
end

app/models/baby.rb
# == Schema Information
#
# Table name: babies
#
#  id          :integer          not null, primary key
#  address     :string(255)
#  birthday    :date
#  father_name :string(255)
#  mother_name :string(255)
#  name        :string(255)
#  phone       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Baby < ApplicationRecord
  has_many :activity_logs
  has_many :activities, through: :activity_logs
  has_many :assistants, through: :activity_logs

  validates :address,:birthday,:father_name,:mother_name,:name,:phone,presence:true

end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name, :birthday, :mother_name, :father_name, :address, :phone)
    end
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_form.html.haml
.mt-5.mb-5
  = form_for @baby do |f|
    - if @baby.errors.any?
      #error_explanation
        %h2= "#{pluralize(@baby.errors.count, "error")} prohibited this baby from being saved:"
        %ul
          - @baby.errors.full_messages.each do |message|
            %li= message

    .form-group
      = f.label :name
      = f.text_field :name,class:"form-control"
    .form-group
      = f.label :birthday
      = f.date_select :birthday,class:"form-control"
    .form-group
      = f.label :mother_name
      = f.text_field :mother_name,class:"form-control"
    .form-group
      = f.label :father_name
      = f.text_field :father_name,class:"form-control"
    .form-group
      = f.label :address
      = f.text_field :address,class:"form-control"
    .form-group
      = f.label :phone
      = f.text_field :phone,class:"form-control"
    .actions.form-group
      = f.submit 'Guardar',class:"btn btn-primary"

app/views/babies/edit.html.haml
.row.justify-content-center
  .col-md-5
    %h1 Editar datos de bebé

    = render 'form'
    .mb-5
      = link_to 'Regresar a lista de bebes', babies_path

app/views/babies/index.html.haml
%h1 Lista de bebés
.mt-5.mb-5
  = link_to 'Inscribir bebé', new_baby_path
%table.table
  %thead
    %tr
      %th Name
      %th Birthday
      %th Mother name
      %th Father name
      %th Address
      %th Phone
      %th
      %th
      %th

  %tbody
    - @babies.each do |baby|
      %tr
        %td= baby.name
        %td.td= baby.birthday
        %td= baby.mother_name
        %td= baby.father_name
        %td= baby.address
        %td.td= baby.phone
        %td= link_to 'Ver', baby
        %td= link_to 'Editar', edit_baby_path(baby)
        %td= link_to 'Eliminar', baby, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/babies/new.html.haml
.row.justify-content-center
  .col-md-4
    %h1 Nuevo bebé

    = render 'form'
    .mb-5
      = link_to 'Regresar a lista de bebes', babies_path

app/views/babies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @baby.name
%p
  %b Birthday:
  = @baby.birthday
%p
  %b Mother name:
  = @baby.mother_name
%p
  %b Father name:
  = @baby.father_name
%p
  %b Address:
  = @baby.address
%p
  %b Phone:
  = @baby.phone

= link_to 'Edit', edit_baby_path(@baby)
\|
= link_to 'Back', babies_path