config/routes.rb
Rails.application.routes.draw do
  
  
 devise_for :users 
  
  authenticate :user do
    
    resources :babies
    resources :assistants
    resources :activity_logs
    resources :activities

    get 'search/create'
    root to:'welcome#index'
    
  end


  unauthenticated :user do
    root to:'welcome#unregistered'
  end
  
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  description :string(255)
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Activity < ApplicationRecord
  has_many :assistants, through: :activity_logs
  has_many :babies, through: :activity_logs
  has_many :activity_logs

  validates :description, :name, presence:true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :description)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name,class:"form-control"
  .form-group
    = f.label :description
    = f.text_field :description,class:"form-control"
  .actions.form-group
  
    = f.submit 'Guardar',class:"btn btn-primary"

app/views/activities/edit.html.haml
.row.justify-content-center
  .col-md-4
    %h1 Editar actividad

    = render 'form'
    .mb-5
      = link_to 'Regresar a actividades', activities_path

app/views/activities/index.html.haml
%h1 Lista de actividades
.mt-5.mb-5
  = link_to 'Nueva Actividad', new_activity_path
%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @activities.each do |activity|
      %tr
        %td.td= activity.name
        %td= activity.description
        %td= link_to 'Ver', activity
        %td= link_to 'Editar', edit_activity_path(activity)
        %td= link_to 'Eliminar', activity, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/activities/new.html.haml
.row.justify-content-center
  .col-md-4
    %h1 Nueva actividad

    = render 'form'
    .mb-5
      = link_to 'Regresar a actividades', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Description:
  = @activity.description

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path